name: Process APK Updates
env:
    TZ: Asia/Shanghai

on:
  push:
    paths:
      - 'apk/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  process-apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone gh-pages branch to fdroid directory
        run: |
          # 这里必须x-access-token因为要蹭到默认token的权限，
          git clone --depth 1 --branch gh-pages https://x-access-token:${{ github.token }}@github.com/${GITHUB_REPOSITORY}.git fdroid
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Initialize submodule
        run: |
          git submodule init fdroid

      - name: Create log directory
        run: mkdir -p log

      - name: Process APK directory
        run: |
          set -o pipefail  # Make sure pipeline status is preserved
          ./script/process-apk-dir.sh 2>&1 | tee "log/process-apk_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}.log"
        continue-on-error: true
        id: process_apk

      - name: Setup F-Droid config and keystore
        if: steps.process_apk.outcome == 'success'
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASS: ${{ secrets.KEYSTOREPASS }}
          KEY_PASS: ${{ secrets.KEYPASS }}
          REPO_KEYALIAS: ${{ secrets.REPO_KEYALIAS }}
          KEY_DNAME: ${{ secrets.KEYDNAME }}
        run: |
          echo "$KEYSTORE" | base64 -d > fdroid/keystore.p12
          echo "repo_keyalias: $REPO_KEYALIAS" >> fdroid/config.yml
          echo "keystore: keystore.p12" >> fdroid/config.yml
          echo "keystorepass: $KEYSTORE_PASS" >> fdroid/config.yml
          echo "keypass: $KEY_PASS" >> fdroid/config.yml
          echo "keydname: $KEY_DNAME" >> fdroid/config.yml
          ./script/update-config.sh ${GITHUB_REPOSITORY}

      - name: Update F-Droid repository
        if: steps.process_apk.outcome == 'success'
        run: ./script/update-fdroid.sh

      - name: Commit changes
        if: steps.process_apk.outcome == 'success'
        run: ./script/commit-fdroid.sh

      - name: Push changes
        if: steps.process_apk.outcome == 'success'
        run: ./script/push-fdroid.sh

      - name: Upload process logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: process-logs
          path: log/
